apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: tu1cwgdmm-python
  janus-idp.io/tekton: tu1cwgdmm-python
  backstage.io/kubernetes-id: tu1cwgdmm-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tu1cwgdmm-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
